const express = require("express");
const router = express.Router();
const { addRoom, updateRoom, deleteRoom, getAllRooms } = require("../controllers/roomControllers");
const upload = require("../config/upload");
const authMiddleware = require("../middlewares/authMiddleware");
const checkOwnerMiddleware = require("../middlewares/checkOwnerMiddleware");
router.post("/", authMiddleware, checkOwnerMiddleware, upload.single("image"), addRoom);
router.put("/:id", authMiddleware, checkOwnerMiddleware, upload.single("image"), updateRoom);
router.delete("/:id", authMiddleware, checkOwnerMiddleware, deleteRoom);
router.get("/:hotelId", getAllRooms);
module.exports = router;